version: '3'
services:
  zookeeper0:
    image: "cloudurable/zookeeper-image:0.2"
    restart: always
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
    environment:
     - ENSEMBLE=zookeeper0,zookeeper1,zookeeper2
     - MY_ID=1
  zookeeper1:
    image: "cloudurable/zookeeper-image:0.2"
    restart: always
    ports:
     - "2182:2181"
     - "2777:2888"
     - "3777:3888"
    environment:
     - ENSEMBLE=zookeeper0,zookeeper1,zookeeper2
     - MY_ID=2
  zookeeper2:
    image: "cloudurable/zookeeper-image:0.2"
    restart: always
    ports:
     - "2183:2181"
     - "2666:2888"
     - "3666:3888"     
    environment:
     - ENSEMBLE=zookeeper0,zookeeper1,zookeeper2
     - MY_ID=3
